version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
    ports:
      - "80:80"
volumes:
  frontend_dist: